
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.clozynoii.slsb.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.clozynoii.slsb.block.SunkenDungeonWestBlock;
import net.clozynoii.slsb.block.SunkenDungeonSouthBlock;
import net.clozynoii.slsb.block.SunkenDungeonNorthBlock;
import net.clozynoii.slsb.block.SunkenDungeonEnemiesBlock;
import net.clozynoii.slsb.block.SunkenDungeonEastBlock;
import net.clozynoii.slsb.block.SunkenDungeonBossBlock;
import net.clozynoii.slsb.block.SubwayDungeonWestBlock;
import net.clozynoii.slsb.block.SubwayDungeonSouthBlock;
import net.clozynoii.slsb.block.SubwayDungeonNorthBlock;
import net.clozynoii.slsb.block.SubwayDungeonEnemiesBlock;
import net.clozynoii.slsb.block.SubwayDungeonEastBlock;
import net.clozynoii.slsb.block.SubwayDungeonBossBlock;
import net.clozynoii.slsb.block.SpiderDungeonWestBlock;
import net.clozynoii.slsb.block.SpiderDungeonSouthBlock;
import net.clozynoii.slsb.block.SpiderDungeonNorthBlock;
import net.clozynoii.slsb.block.SpiderDungeonEnemiesBlock;
import net.clozynoii.slsb.block.SpiderDungeonEastBlock;
import net.clozynoii.slsb.block.SpiderDungeonBossBlock;
import net.clozynoii.slsb.block.SandDungeonWestBlock;
import net.clozynoii.slsb.block.SandDungeonSouthBlock;
import net.clozynoii.slsb.block.SandDungeonNorthBlock;
import net.clozynoii.slsb.block.SandDungeonEnemiesBlock;
import net.clozynoii.slsb.block.SandDungeonEastBlock;
import net.clozynoii.slsb.block.SandDungeonBossBlock;
import net.clozynoii.slsb.block.RedGateSmallBlock;
import net.clozynoii.slsb.block.RedGateMediumBlock;
import net.clozynoii.slsb.block.RatDungeonWestBlock;
import net.clozynoii.slsb.block.RatDungeonSouthBlock;
import net.clozynoii.slsb.block.RatDungeonNorthBlock;
import net.clozynoii.slsb.block.RatDungeonEnemiesBlock;
import net.clozynoii.slsb.block.RatDungeonEastBlock;
import net.clozynoii.slsb.block.RatDungeonBossBlock;
import net.clozynoii.slsb.block.OrcDungeonWestBlock;
import net.clozynoii.slsb.block.OrcDungeonSouthBlock;
import net.clozynoii.slsb.block.OrcDungeonNorthBlock;
import net.clozynoii.slsb.block.OrcDungeonEnemiesBlock;
import net.clozynoii.slsb.block.OrcDungeonEastBlock;
import net.clozynoii.slsb.block.OrcDungeonBossBlock;
import net.clozynoii.slsb.block.NagaDungeonWestBlock;
import net.clozynoii.slsb.block.NagaDungeonSouthBlock;
import net.clozynoii.slsb.block.NagaDungeonNorthBlock;
import net.clozynoii.slsb.block.NagaDungeonEnemiesBlock;
import net.clozynoii.slsb.block.NagaDungeonEastBlock;
import net.clozynoii.slsb.block.NagaDungeonBossBlock;
import net.clozynoii.slsb.block.MineDungeonWestBlock;
import net.clozynoii.slsb.block.MineDungeonSouthBlock;
import net.clozynoii.slsb.block.MineDungeonNorthBlock;
import net.clozynoii.slsb.block.MineDungeonEnemiesBlock;
import net.clozynoii.slsb.block.MineDungeonEastBlock;
import net.clozynoii.slsb.block.MineDungeonBossBlock;
import net.clozynoii.slsb.block.MazeDungeonWestBlock;
import net.clozynoii.slsb.block.MazeDungeonSouthBlock;
import net.clozynoii.slsb.block.MazeDungeonNorthBlock;
import net.clozynoii.slsb.block.MazeDungeonEnemiesBlock;
import net.clozynoii.slsb.block.MazeDungeonEastBlock;
import net.clozynoii.slsb.block.MazeDungeonBossBlock;
import net.clozynoii.slsb.block.ManaCrystalBlockStoneBlock;
import net.clozynoii.slsb.block.ManaCrystalBlockPureBlock;
import net.clozynoii.slsb.block.ManaCrystalBlockGraniteBlock;
import net.clozynoii.slsb.block.ManaCrystalBlockDripstoneBlock;
import net.clozynoii.slsb.block.ManaCrystalBlockDioriteBlock;
import net.clozynoii.slsb.block.ManaCrystalBlockDeepslateBlock;
import net.clozynoii.slsb.block.LichDungeonWestBlock;
import net.clozynoii.slsb.block.LichDungeonSouthBlock;
import net.clozynoii.slsb.block.LichDungeonNorthBlock;
import net.clozynoii.slsb.block.LichDungeonEnemiesBlock;
import net.clozynoii.slsb.block.LichDungeonEastBlock;
import net.clozynoii.slsb.block.LichDungeonBossBlock;
import net.clozynoii.slsb.block.LibraryDungeonWestBlock;
import net.clozynoii.slsb.block.LibraryDungeonSouthBlock;
import net.clozynoii.slsb.block.LibraryDungeonNorthBlock;
import net.clozynoii.slsb.block.LibraryDungeonEnemiesBlock;
import net.clozynoii.slsb.block.LibraryDungeonEastBlock;
import net.clozynoii.slsb.block.LibraryDungeonBossBlock;
import net.clozynoii.slsb.block.IceDungeonWestBlock;
import net.clozynoii.slsb.block.IceDungeonSouthBlock;
import net.clozynoii.slsb.block.IceDungeonNorthBlock;
import net.clozynoii.slsb.block.IceDungeonEnemiesBlock;
import net.clozynoii.slsb.block.IceDungeonEastBlock;
import net.clozynoii.slsb.block.IceDungeonBossBlock;
import net.clozynoii.slsb.block.GoblinDungeonWestBlock;
import net.clozynoii.slsb.block.GoblinDungeonSouthBlock;
import net.clozynoii.slsb.block.GoblinDungeonNorthBlock;
import net.clozynoii.slsb.block.GoblinDungeonEnemiesBlock;
import net.clozynoii.slsb.block.GoblinDungeonEastBlock;
import net.clozynoii.slsb.block.GoblinDungeonBossBlock;
import net.clozynoii.slsb.block.GiantDungeonWestBlock;
import net.clozynoii.slsb.block.GiantDungeonSouthBlock;
import net.clozynoii.slsb.block.GiantDungeonNorthBlock;
import net.clozynoii.slsb.block.GiantDungeonEnemiesBlock;
import net.clozynoii.slsb.block.GiantDungeonEastBlock;
import net.clozynoii.slsb.block.GiantDungeonBossBlock;
import net.clozynoii.slsb.block.ForestDungeonWestBlock;
import net.clozynoii.slsb.block.ForestDungeonSouthBlock;
import net.clozynoii.slsb.block.ForestDungeonNorthBlock;
import net.clozynoii.slsb.block.ForestDungeonEnemiesBlock;
import net.clozynoii.slsb.block.ForestDungeonEastBlock;
import net.clozynoii.slsb.block.ForestDungeonBossBlock;
import net.clozynoii.slsb.block.DragonDungeonWestBlock;
import net.clozynoii.slsb.block.DragonDungeonSouthBlock;
import net.clozynoii.slsb.block.DragonDungeonNorthBlock;
import net.clozynoii.slsb.block.DragonDungeonEnemiesBlock;
import net.clozynoii.slsb.block.DragonDungeonEastBlock;
import net.clozynoii.slsb.block.DragonDungeonBossBlock;
import net.clozynoii.slsb.block.DoubleDungeonWestBlock;
import net.clozynoii.slsb.block.DoubleDungeonSouthBlock;
import net.clozynoii.slsb.block.DoubleDungeonNorthBlock;
import net.clozynoii.slsb.block.DoubleDungeonEnemiesBlock;
import net.clozynoii.slsb.block.DoubleDungeonEastBlock;
import net.clozynoii.slsb.block.DoubleDungeonBossBlock;
import net.clozynoii.slsb.block.CrystalDungeonWestBlock;
import net.clozynoii.slsb.block.CrystalDungeonSouthBlock;
import net.clozynoii.slsb.block.CrystalDungeonNorthBlock;
import net.clozynoii.slsb.block.CrystalDungeonEnemiesBlock;
import net.clozynoii.slsb.block.CrystalDungeonEastBlock;
import net.clozynoii.slsb.block.CrystalDungeonBossBlock;
import net.clozynoii.slsb.block.ColiseumDungeonWestBlock;
import net.clozynoii.slsb.block.ColiseumDungeonSouthBlock;
import net.clozynoii.slsb.block.ColiseumDungeonNorthBlock;
import net.clozynoii.slsb.block.ColiseumDungeonEnemiesBlock;
import net.clozynoii.slsb.block.ColiseumDungeonEastBlock;
import net.clozynoii.slsb.block.ColiseumDungeonBossBlock;
import net.clozynoii.slsb.block.CathedralDungeonWestBlock;
import net.clozynoii.slsb.block.CathedralDungeonSouthBlock;
import net.clozynoii.slsb.block.CathedralDungeonNorthBlock;
import net.clozynoii.slsb.block.CathedralDungeonEnemiesBlock;
import net.clozynoii.slsb.block.CathedralDungeonEastBlock;
import net.clozynoii.slsb.block.CathedralDungeonBossBlock;
import net.clozynoii.slsb.block.CatacombDungeonWestBlock;
import net.clozynoii.slsb.block.CatacombDungeonSouthBlock;
import net.clozynoii.slsb.block.CatacombDungeonNorthBlock;
import net.clozynoii.slsb.block.CatacombDungeonEnemiesBlock;
import net.clozynoii.slsb.block.CatacombDungeonEastBlock;
import net.clozynoii.slsb.block.CatacombDungeonBossBlock;
import net.clozynoii.slsb.block.BlueGateSmallBlock;
import net.clozynoii.slsb.block.BlueGateMediumBlock;
import net.clozynoii.slsb.block.AwakeningOrbBlock;
import net.clozynoii.slsb.SlsbMod;

public class SlsbModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, SlsbMod.MODID);
	public static final RegistryObject<Block> BLUE_GATE_SMALL = REGISTRY.register("blue_gate_small", () -> new BlueGateSmallBlock());
	public static final RegistryObject<Block> RED_GATE_SMALL = REGISTRY.register("red_gate_small", () -> new RedGateSmallBlock());
	public static final RegistryObject<Block> BLUE_GATE_MEDIUM = REGISTRY.register("blue_gate_medium", () -> new BlueGateMediumBlock());
	public static final RegistryObject<Block> MANA_CRYSTAL_BLOCK_STONE = REGISTRY.register("mana_crystal_block_stone", () -> new ManaCrystalBlockStoneBlock());
	public static final RegistryObject<Block> MANA_CRYSTAL_BLOCK_PURE = REGISTRY.register("mana_crystal_block_pure", () -> new ManaCrystalBlockPureBlock());
	public static final RegistryObject<Block> MANA_CRYSTAL_BLOCK_DEEPSLATE = REGISTRY.register("mana_crystal_block_deepslate", () -> new ManaCrystalBlockDeepslateBlock());
	public static final RegistryObject<Block> MANA_CRYSTAL_BLOCK_DIORITE = REGISTRY.register("mana_crystal_block_diorite", () -> new ManaCrystalBlockDioriteBlock());
	public static final RegistryObject<Block> MANA_CRYSTAL_BLOCK_GRANITE = REGISTRY.register("mana_crystal_block_granite", () -> new ManaCrystalBlockGraniteBlock());
	public static final RegistryObject<Block> MANA_CRYSTAL_BLOCK_DRIPSTONE = REGISTRY.register("mana_crystal_block_dripstone", () -> new ManaCrystalBlockDripstoneBlock());
	public static final RegistryObject<Block> AWAKENING_ORB = REGISTRY.register("awakening_orb", () -> new AwakeningOrbBlock());
	public static final RegistryObject<Block> RAT_DUNGEON_NORTH = REGISTRY.register("rat_dungeon_north", () -> new RatDungeonNorthBlock());
	public static final RegistryObject<Block> RAT_DUNGEON_EAST = REGISTRY.register("rat_dungeon_east", () -> new RatDungeonEastBlock());
	public static final RegistryObject<Block> RAT_DUNGEON_SOUTH = REGISTRY.register("rat_dungeon_south", () -> new RatDungeonSouthBlock());
	public static final RegistryObject<Block> RAT_DUNGEON_WEST = REGISTRY.register("rat_dungeon_west", () -> new RatDungeonWestBlock());
	public static final RegistryObject<Block> MINE_DUNGEON_NORTH = REGISTRY.register("mine_dungeon_north", () -> new MineDungeonNorthBlock());
	public static final RegistryObject<Block> MINE_DUNGEON_EAST = REGISTRY.register("mine_dungeon_east", () -> new MineDungeonEastBlock());
	public static final RegistryObject<Block> MINE_DUNGEON_SOUTH = REGISTRY.register("mine_dungeon_south", () -> new MineDungeonSouthBlock());
	public static final RegistryObject<Block> MINE_DUNGEON_WEST = REGISTRY.register("mine_dungeon_west", () -> new MineDungeonWestBlock());
	public static final RegistryObject<Block> FOREST_DUNGEON_NORTH = REGISTRY.register("forest_dungeon_north", () -> new ForestDungeonNorthBlock());
	public static final RegistryObject<Block> FOREST_DUNGEON_EAST = REGISTRY.register("forest_dungeon_east", () -> new ForestDungeonEastBlock());
	public static final RegistryObject<Block> FOREST_DUNGEON_SOUTH = REGISTRY.register("forest_dungeon_south", () -> new ForestDungeonSouthBlock());
	public static final RegistryObject<Block> FOREST_DUNGEON_WEST = REGISTRY.register("forest_dungeon_west", () -> new ForestDungeonWestBlock());
	public static final RegistryObject<Block> SUBWAY_DUNGEON_NORTH = REGISTRY.register("subway_dungeon_north", () -> new SubwayDungeonNorthBlock());
	public static final RegistryObject<Block> SUBWAY_DUNGEON_EAST = REGISTRY.register("subway_dungeon_east", () -> new SubwayDungeonEastBlock());
	public static final RegistryObject<Block> SUBWAY_DUNGEON_SOUTH = REGISTRY.register("subway_dungeon_south", () -> new SubwayDungeonSouthBlock());
	public static final RegistryObject<Block> SUBWAY_DUNGEON_WEST = REGISTRY.register("subway_dungeon_west", () -> new SubwayDungeonWestBlock());
	public static final RegistryObject<Block> RAT_DUNGEON_ENEMIES = REGISTRY.register("rat_dungeon_enemies", () -> new RatDungeonEnemiesBlock());
	public static final RegistryObject<Block> RAT_DUNGEON_BOSS = REGISTRY.register("rat_dungeon_boss", () -> new RatDungeonBossBlock());
	public static final RegistryObject<Block> MINE_DUNGEON_ENEMIES = REGISTRY.register("mine_dungeon_enemies", () -> new MineDungeonEnemiesBlock());
	public static final RegistryObject<Block> MINE_DUNGEON_BOSS = REGISTRY.register("mine_dungeon_boss", () -> new MineDungeonBossBlock());
	public static final RegistryObject<Block> FOREST_DUNGEON_ENEMIES = REGISTRY.register("forest_dungeon_enemies", () -> new ForestDungeonEnemiesBlock());
	public static final RegistryObject<Block> FOREST_DUNGEON_BOSS = REGISTRY.register("forest_dungeon_boss", () -> new ForestDungeonBossBlock());
	public static final RegistryObject<Block> SUBWAY_DUNGEON_ENEMIES = REGISTRY.register("subway_dungeon_enemies", () -> new SubwayDungeonEnemiesBlock());
	public static final RegistryObject<Block> SUBWAY_DUNGEON_BOSS = REGISTRY.register("subway_dungeon_boss", () -> new SubwayDungeonBossBlock());
	public static final RegistryObject<Block> CATACOMB_DUNGEON_NORTH = REGISTRY.register("catacomb_dungeon_north", () -> new CatacombDungeonNorthBlock());
	public static final RegistryObject<Block> CATACOMB_DUNGEON_EAST = REGISTRY.register("catacomb_dungeon_east", () -> new CatacombDungeonEastBlock());
	public static final RegistryObject<Block> CATACOMB_DUNGEON_SOUTH = REGISTRY.register("catacomb_dungeon_south", () -> new CatacombDungeonSouthBlock());
	public static final RegistryObject<Block> CATACOMB_DUNGEON_WEST = REGISTRY.register("catacomb_dungeon_west", () -> new CatacombDungeonWestBlock());
	public static final RegistryObject<Block> CATACOMB_DUNGEON_ENEMIES = REGISTRY.register("catacomb_dungeon_enemies", () -> new CatacombDungeonEnemiesBlock());
	public static final RegistryObject<Block> CATACOMB_DUNGEON_BOSS = REGISTRY.register("catacomb_dungeon_boss", () -> new CatacombDungeonBossBlock());
	public static final RegistryObject<Block> SPIDER_DUNGEON_NORTH = REGISTRY.register("spider_dungeon_north", () -> new SpiderDungeonNorthBlock());
	public static final RegistryObject<Block> SPIDER_DUNGEON_EAST = REGISTRY.register("spider_dungeon_east", () -> new SpiderDungeonEastBlock());
	public static final RegistryObject<Block> SPIDER_DUNGEON_SOUTH = REGISTRY.register("spider_dungeon_south", () -> new SpiderDungeonSouthBlock());
	public static final RegistryObject<Block> SPIDER_DUNGEON_WEST = REGISTRY.register("spider_dungeon_west", () -> new SpiderDungeonWestBlock());
	public static final RegistryObject<Block> SPIDER_DUNGEON_ENEMIES = REGISTRY.register("spider_dungeon_enemies", () -> new SpiderDungeonEnemiesBlock());
	public static final RegistryObject<Block> SPIDER_DUNGEON_BOSS = REGISTRY.register("spider_dungeon_boss", () -> new SpiderDungeonBossBlock());
	public static final RegistryObject<Block> SUNKEN_DUNGEON_NORTH = REGISTRY.register("sunken_dungeon_north", () -> new SunkenDungeonNorthBlock());
	public static final RegistryObject<Block> SUNKEN_DUNGEON_EAST = REGISTRY.register("sunken_dungeon_east", () -> new SunkenDungeonEastBlock());
	public static final RegistryObject<Block> SUNKEN_DUNGEON_SOUTH = REGISTRY.register("sunken_dungeon_south", () -> new SunkenDungeonSouthBlock());
	public static final RegistryObject<Block> SUNKEN_DUNGEON_WEST = REGISTRY.register("sunken_dungeon_west", () -> new SunkenDungeonWestBlock());
	public static final RegistryObject<Block> SUNKEN_DUNGEON_ENEMIES = REGISTRY.register("sunken_dungeon_enemies", () -> new SunkenDungeonEnemiesBlock());
	public static final RegistryObject<Block> SUNKEN_DUNGEON_BOSS = REGISTRY.register("sunken_dungeon_boss", () -> new SunkenDungeonBossBlock());
	public static final RegistryObject<Block> ICE_DUNGEON_NORTH = REGISTRY.register("ice_dungeon_north", () -> new IceDungeonNorthBlock());
	public static final RegistryObject<Block> ICE_DUNGEON_EAST = REGISTRY.register("ice_dungeon_east", () -> new IceDungeonEastBlock());
	public static final RegistryObject<Block> ICE_DUNGEON_SOUTH = REGISTRY.register("ice_dungeon_south", () -> new IceDungeonSouthBlock());
	public static final RegistryObject<Block> ICE_DUNGEON_WEST = REGISTRY.register("ice_dungeon_west", () -> new IceDungeonWestBlock());
	public static final RegistryObject<Block> ICE_DUNGEON_ENEMIES = REGISTRY.register("ice_dungeon_enemies", () -> new IceDungeonEnemiesBlock());
	public static final RegistryObject<Block> ICE_DUNGEON_BOSS = REGISTRY.register("ice_dungeon_boss", () -> new IceDungeonBossBlock());
	public static final RegistryObject<Block> DOUBLE_DUNGEON_NORTH = REGISTRY.register("double_dungeon_north", () -> new DoubleDungeonNorthBlock());
	public static final RegistryObject<Block> DOUBLE_DUNGEON_EAST = REGISTRY.register("double_dungeon_east", () -> new DoubleDungeonEastBlock());
	public static final RegistryObject<Block> DOUBLE_DUNGEON_SOUTH = REGISTRY.register("double_dungeon_south", () -> new DoubleDungeonSouthBlock());
	public static final RegistryObject<Block> DOUBLE_DUNGEON_WEST = REGISTRY.register("double_dungeon_west", () -> new DoubleDungeonWestBlock());
	public static final RegistryObject<Block> DOUBLE_DUNGEON_ENEMIES = REGISTRY.register("double_dungeon_enemies", () -> new DoubleDungeonEnemiesBlock());
	public static final RegistryObject<Block> DOUBLE_DUNGEON_BOSS = REGISTRY.register("double_dungeon_boss", () -> new DoubleDungeonBossBlock());
	public static final RegistryObject<Block> LIBRARY_DUNGEON_NORTH = REGISTRY.register("library_dungeon_north", () -> new LibraryDungeonNorthBlock());
	public static final RegistryObject<Block> LIBRARY_DUNGEON_EAST = REGISTRY.register("library_dungeon_east", () -> new LibraryDungeonEastBlock());
	public static final RegistryObject<Block> LIBRARY_DUNGEON_SOUTH = REGISTRY.register("library_dungeon_south", () -> new LibraryDungeonSouthBlock());
	public static final RegistryObject<Block> LIBRARY_DUNGEON_WEST = REGISTRY.register("library_dungeon_west", () -> new LibraryDungeonWestBlock());
	public static final RegistryObject<Block> LIBRARY_DUNGEON_ENEMIES = REGISTRY.register("library_dungeon_enemies", () -> new LibraryDungeonEnemiesBlock());
	public static final RegistryObject<Block> LIBRARY_DUNGEON_BOSS = REGISTRY.register("library_dungeon_boss", () -> new LibraryDungeonBossBlock());
	public static final RegistryObject<Block> MAZE_DUNGEON_NORTH = REGISTRY.register("maze_dungeon_north", () -> new MazeDungeonNorthBlock());
	public static final RegistryObject<Block> MAZE_DUNGEON_EAST = REGISTRY.register("maze_dungeon_east", () -> new MazeDungeonEastBlock());
	public static final RegistryObject<Block> MAZE_DUNGEON_SOUTH = REGISTRY.register("maze_dungeon_south", () -> new MazeDungeonSouthBlock());
	public static final RegistryObject<Block> MAZE_DUNGEON_WEST = REGISTRY.register("maze_dungeon_west", () -> new MazeDungeonWestBlock());
	public static final RegistryObject<Block> MAZE_DUNGEON_ENEMIES = REGISTRY.register("maze_dungeon_enemies", () -> new MazeDungeonEnemiesBlock());
	public static final RegistryObject<Block> MAZE_DUNGEON_BOSS = REGISTRY.register("maze_dungeon_boss", () -> new MazeDungeonBossBlock());
	public static final RegistryObject<Block> GOBLIN_DUNGEON_NORTH = REGISTRY.register("goblin_dungeon_north", () -> new GoblinDungeonNorthBlock());
	public static final RegistryObject<Block> GOBLIN_DUNGEON_EAST = REGISTRY.register("goblin_dungeon_east", () -> new GoblinDungeonEastBlock());
	public static final RegistryObject<Block> GOBLIN_DUNGEON_SOUTH = REGISTRY.register("goblin_dungeon_south", () -> new GoblinDungeonSouthBlock());
	public static final RegistryObject<Block> GOBLIN_DUNGEON_WEST = REGISTRY.register("goblin_dungeon_west", () -> new GoblinDungeonWestBlock());
	public static final RegistryObject<Block> GOBLIN_DUNGEON_ENEMIES = REGISTRY.register("goblin_dungeon_enemies", () -> new GoblinDungeonEnemiesBlock());
	public static final RegistryObject<Block> GOBLIN_DUNGEON_BOSS = REGISTRY.register("goblin_dungeon_boss", () -> new GoblinDungeonBossBlock());
	public static final RegistryObject<Block> SAND_DUNGEON_NORTH = REGISTRY.register("sand_dungeon_north", () -> new SandDungeonNorthBlock());
	public static final RegistryObject<Block> SAND_DUNGEON_EAST = REGISTRY.register("sand_dungeon_east", () -> new SandDungeonEastBlock());
	public static final RegistryObject<Block> SAND_DUNGEON_SOUTH = REGISTRY.register("sand_dungeon_south", () -> new SandDungeonSouthBlock());
	public static final RegistryObject<Block> SAND_DUNGEON_WEST = REGISTRY.register("sand_dungeon_west", () -> new SandDungeonWestBlock());
	public static final RegistryObject<Block> SAND_DUNGEON_ENEMIES = REGISTRY.register("sand_dungeon_enemies", () -> new SandDungeonEnemiesBlock());
	public static final RegistryObject<Block> SAND_DUNGEON_BOSS = REGISTRY.register("sand_dungeon_boss", () -> new SandDungeonBossBlock());
	public static final RegistryObject<Block> CRYSTAL_DUNGEON_NORTH = REGISTRY.register("crystal_dungeon_north", () -> new CrystalDungeonNorthBlock());
	public static final RegistryObject<Block> CRYSTAL_DUNGEON_EAST = REGISTRY.register("crystal_dungeon_east", () -> new CrystalDungeonEastBlock());
	public static final RegistryObject<Block> CRYSTAL_DUNGEON_SOUTH = REGISTRY.register("crystal_dungeon_south", () -> new CrystalDungeonSouthBlock());
	public static final RegistryObject<Block> CRYSTAL_DUNGEON_WEST = REGISTRY.register("crystal_dungeon_west", () -> new CrystalDungeonWestBlock());
	public static final RegistryObject<Block> CRYSTAL_DUNGEON_ENEMIES = REGISTRY.register("crystal_dungeon_enemies", () -> new CrystalDungeonEnemiesBlock());
	public static final RegistryObject<Block> CRYSTAL_DUNGEON_BOSS = REGISTRY.register("crystal_dungeon_boss", () -> new CrystalDungeonBossBlock());
	public static final RegistryObject<Block> COLISEUM_DUNGEON_NORTH = REGISTRY.register("coliseum_dungeon_north", () -> new ColiseumDungeonNorthBlock());
	public static final RegistryObject<Block> COLISEUM_DUNGEON_EAST = REGISTRY.register("coliseum_dungeon_east", () -> new ColiseumDungeonEastBlock());
	public static final RegistryObject<Block> COLISEUM_DUNGEON_SOUTH = REGISTRY.register("coliseum_dungeon_south", () -> new ColiseumDungeonSouthBlock());
	public static final RegistryObject<Block> COLISEUM_DUNGEON_WEST = REGISTRY.register("coliseum_dungeon_west", () -> new ColiseumDungeonWestBlock());
	public static final RegistryObject<Block> COLISEUM_DUNGEON_ENEMIES = REGISTRY.register("coliseum_dungeon_enemies", () -> new ColiseumDungeonEnemiesBlock());
	public static final RegistryObject<Block> COLISEUM_DUNGEON_BOSS = REGISTRY.register("coliseum_dungeon_boss", () -> new ColiseumDungeonBossBlock());
	public static final RegistryObject<Block> ORC_DUNGEON_NORTH = REGISTRY.register("orc_dungeon_north", () -> new OrcDungeonNorthBlock());
	public static final RegistryObject<Block> ORC_DUNGEON_EAST = REGISTRY.register("orc_dungeon_east", () -> new OrcDungeonEastBlock());
	public static final RegistryObject<Block> ORC_DUNGEON_SOUTH = REGISTRY.register("orc_dungeon_south", () -> new OrcDungeonSouthBlock());
	public static final RegistryObject<Block> ORC_DUNGEON_WEST = REGISTRY.register("orc_dungeon_west", () -> new OrcDungeonWestBlock());
	public static final RegistryObject<Block> ORC_DUNGEON_ENEMIES = REGISTRY.register("orc_dungeon_enemies", () -> new OrcDungeonEnemiesBlock());
	public static final RegistryObject<Block> ORC_DUNGEON_BOSS = REGISTRY.register("orc_dungeon_boss", () -> new OrcDungeonBossBlock());
	public static final RegistryObject<Block> LICH_DUNGEON_NORTH = REGISTRY.register("lich_dungeon_north", () -> new LichDungeonNorthBlock());
	public static final RegistryObject<Block> LICH_DUNGEON_EAST = REGISTRY.register("lich_dungeon_east", () -> new LichDungeonEastBlock());
	public static final RegistryObject<Block> LICH_DUNGEON_SOUTH = REGISTRY.register("lich_dungeon_south", () -> new LichDungeonSouthBlock());
	public static final RegistryObject<Block> LICH_DUNGEON_WEST = REGISTRY.register("lich_dungeon_west", () -> new LichDungeonWestBlock());
	public static final RegistryObject<Block> LICH_DUNGEON_ENEMIES = REGISTRY.register("lich_dungeon_enemies", () -> new LichDungeonEnemiesBlock());
	public static final RegistryObject<Block> LICH_DUNGEON_BOSS = REGISTRY.register("lich_dungeon_boss", () -> new LichDungeonBossBlock());
	public static final RegistryObject<Block> NAGA_DUNGEON_NORTH = REGISTRY.register("naga_dungeon_north", () -> new NagaDungeonNorthBlock());
	public static final RegistryObject<Block> NAGA_DUNGEON_EAST = REGISTRY.register("naga_dungeon_east", () -> new NagaDungeonEastBlock());
	public static final RegistryObject<Block> NAGA_DUNGEON_SOUTH = REGISTRY.register("naga_dungeon_south", () -> new NagaDungeonSouthBlock());
	public static final RegistryObject<Block> NAGA_DUNGEON_WEST = REGISTRY.register("naga_dungeon_west", () -> new NagaDungeonWestBlock());
	public static final RegistryObject<Block> NAGA_DUNGEON_ENEMIES = REGISTRY.register("naga_dungeon_enemies", () -> new NagaDungeonEnemiesBlock());
	public static final RegistryObject<Block> NAGA_DUNGEON_BOSS = REGISTRY.register("naga_dungeon_boss", () -> new NagaDungeonBossBlock());
	public static final RegistryObject<Block> DRAGON_DUNGEON_NORTH = REGISTRY.register("dragon_dungeon_north", () -> new DragonDungeonNorthBlock());
	public static final RegistryObject<Block> DRAGON_DUNGEON_EAST = REGISTRY.register("dragon_dungeon_east", () -> new DragonDungeonEastBlock());
	public static final RegistryObject<Block> DRAGON_DUNGEON_SOUTH = REGISTRY.register("dragon_dungeon_south", () -> new DragonDungeonSouthBlock());
	public static final RegistryObject<Block> DRAGON_DUNGEON_WEST = REGISTRY.register("dragon_dungeon_west", () -> new DragonDungeonWestBlock());
	public static final RegistryObject<Block> DRAGON_DUNGEON_ENEMIES = REGISTRY.register("dragon_dungeon_enemies", () -> new DragonDungeonEnemiesBlock());
	public static final RegistryObject<Block> DRAGON_DUNGEON_BOSS = REGISTRY.register("dragon_dungeon_boss", () -> new DragonDungeonBossBlock());
	public static final RegistryObject<Block> GIANT_DUNGEON_NORTH = REGISTRY.register("giant_dungeon_north", () -> new GiantDungeonNorthBlock());
	public static final RegistryObject<Block> GIANT_DUNGEON_EAST = REGISTRY.register("giant_dungeon_east", () -> new GiantDungeonEastBlock());
	public static final RegistryObject<Block> GIANT_DUNGEON_SOUTH = REGISTRY.register("giant_dungeon_south", () -> new GiantDungeonSouthBlock());
	public static final RegistryObject<Block> GIANT_DUNGEON_WEST = REGISTRY.register("giant_dungeon_west", () -> new GiantDungeonWestBlock());
	public static final RegistryObject<Block> GIANT_DUNGEON_ENEMIES = REGISTRY.register("giant_dungeon_enemies", () -> new GiantDungeonEnemiesBlock());
	public static final RegistryObject<Block> GIANT_DUNGEON_BOSS = REGISTRY.register("giant_dungeon_boss", () -> new GiantDungeonBossBlock());
	public static final RegistryObject<Block> CATHEDRAL_DUNGEON_NORTH = REGISTRY.register("cathedral_dungeon_north", () -> new CathedralDungeonNorthBlock());
	public static final RegistryObject<Block> CATHEDRAL_DUNGEON_EAST = REGISTRY.register("cathedral_dungeon_east", () -> new CathedralDungeonEastBlock());
	public static final RegistryObject<Block> CATHEDRAL_DUNGEON_SOUTH = REGISTRY.register("cathedral_dungeon_south", () -> new CathedralDungeonSouthBlock());
	public static final RegistryObject<Block> CATHEDRAL_DUNGEON_WEST = REGISTRY.register("cathedral_dungeon_west", () -> new CathedralDungeonWestBlock());
	public static final RegistryObject<Block> CATHEDRAL_DUNGEON_ENEMIES = REGISTRY.register("cathedral_dungeon_enemies", () -> new CathedralDungeonEnemiesBlock());
	public static final RegistryObject<Block> CATHEDRAL_DUNGEON_BOSS = REGISTRY.register("cathedral_dungeon_boss", () -> new CathedralDungeonBossBlock());
	public static final RegistryObject<Block> RED_GATE_MEDIUM = REGISTRY.register("red_gate_medium", () -> new RedGateMediumBlock());
}
